all:
	gcc -o calloc.o calloc.c 
	gcc -o cli1.o cli1.c 
	gcc -o cli2.o cli2.c 
	gcc -o create_process.o create_process.c 
	gcc -o env1.o env1.c 
	gcc -o env2.o env2.c 
	gcc -o env3.o env3.c 
	gcc -o fork_1.o fork_1.c 
	gcc -o malloc.o malloc.c 
	gcc -o orphan.o orphan.c 
	gcc -o p1_execv.o p1_execv.c 
	gcc -o p1.o p1.c 
	gcc -o p2_execv.o p2_execv.c 
	gcc -o p2.o p2.c 
	gcc -o program1_fork.o program1_fork.c 
	gcc -o program1.o program1.c 
	gcc -o program2.o program2.c 
	gcc -o program2_execl.o program2_execl.c 
	gcc -o wait_1.o wait_1.c 
	gcc -o wait_2.o wait_2.c 
	gcc -o waitpid_3.o waitpid_3.c 
	gcc -o waitpid_4.o waitpid_4.c 
	gcc -o zombie1.o zombie1.c 
	gcc -o zombie2.o zombie2.c 

clean:
	@rm -f *.o